---
services:
  zot:
    image: ghcr.io/project-zot/zot:latest
    ports:
      - "9000:8080"
    volumes:
      - ./hack/tests/zot.config.json:/etc/zot/config.json:ro
      - zot-data:/tmp/zot
    command: ["serve", "/etc/zot/config.json"]

  tpa:
    build:
      context: .
      dockerfile: hack/tests/Containerfile.tpa
    ports:
      - "8080:8080"

volumes:
  zot-data:
