---
name: Test and Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:


jobs:
  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Install Hadolint via Brew
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          /home/linuxbrew/.linuxbrew/bin/brew install hadolint
          sudo ln -s /home/linuxbrew/.linuxbrew/bin/hadolint /usr/bin/

      - name: Run Tests
        run: |
            poetry run tox

  commitlint:
    name: Conventional Commit Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - uses: webiny/action-conventional-commits@v1.3.0
